# -*- coding: utf-8 -*-
"""validation_schema.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mTsy_ZdO3CsJSBIri33Oi4DAF_LKiDTZ
"""

!pip install pandera

import pandera as pa
from pandera import Column, Check

sales_schema = pa.DataFrameSchema({
    "Units Sold": Column(int, Check.ge(0)),
    "Unit Price": Column(float, Check.ge(0)),
    "Sales Channel": Column(str, Check.isin(["Online", "Offline"]))
})